name: cicd pipeline

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup java jdk
      uses: actions/setup-java@v4
      with:
        version: '17'
        distribution: temurin
        cache: maven
        
        cashe: maven
    - name: build with maven
      run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    steps:
     - name : checkout the repo
       uses: actions/checkout@v4

     - name: trivy installtion
       run: |
         sudo apt-get install wget gnupg
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update -y
         sudo apt-get install trivy -y

     - name: trivy  fs
       run: trivy fs --format table -o fs-report.json .

     - name: git leaks install
       run: sudo apt update & sudo apt install gitleaks -y


   
     
    
  
