name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Build application
      run: |
        mvn clean package -DskipTests

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Push Docker Image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/bankapp:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ secrets.AKS_NAME }} \
          --overwrite-existing

    - name: Update Deployment Image
      run: |
        kubectl set image deployment/bankapp bankapp=$IMAGE

    - name: Apply Manifests (if first time deploy)
      run: |
        kubectl apply -f ds.yaml/ || true
